### ISSUE TITLE
OnCentos

### ISSUE THREAD

**Issue by aloudahi** [prateekchandan/Remote-Desktop-Connection#1]
Hello!

Please, how can I use it on centos?

**Comment by aloudahi** [comment]
I got this error:
**Can't open display
Traceback (most recent call last):
  File "server.py", line 12, in <module>
    width,height =[int(a) for a in str(subprocess.check_output("xrandr | grep '*' | awk '{print $1}'", shell=True))[2:-3].split('x')]
  File "server.py", line 12, in <listcomp>
    width,height =[int(a) for a in str(subprocess.check_output("xrandr | grep '*' | awk '{print $1}'", shell=True))[2:-3].split('x')]
ValueError: invalid literal for int() with base 10: ''**
